<div id="cemiterio">

</div>
<div style="margin: 0 auto;width: 900px;">
    <?= $_SESSION['player'] ?>
    <input type="hidden" value="<?= $_SESSION['player'] ?>" id="player">
    <input type="text" value="" id="oponente">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9">
                    <div id="tabuleiro" class="tabuleiro form-control">
                        <div id="taboponente" class="col-lg-12" style="height: 245px;">

                        </div>
                        <div id="tabplayer" class="col-lg-12" style="height: 245px;">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="top: 55px; position: absolute;right: 40px;" draggable="true">
    <div class="row">
        <div class="col-lg-12">
            <div id="mensagens" class="form-control" style="display: block;height: 300px;overflow: auto;"></div>

        </div>
        <div class="col-lg-9">
            <input type="text" class="form-control" id="men_envia"/>
        </div>
        <div class="col-lg-3">
            <button type="button" class="btn btn-default form-control" onclick="conversar();">Enviar</button>
        </div>
    </div>

</div>


<div class="modal fade" id="iniciar" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content"  style="height: 400px;">
            <div class="modal-header bg-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span></span> Selecione uma opção</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-4">
                        <button class="btn btn-info  form-control">Opções</button>
                        <button class="btn btn-success form-control" onclick="conectar();">Conectar</button>
                    </div>
                    <div class="col-lg-8">
                        <div id="conectados">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="maojogador">
    <div class="col-lg-12">

    </div>
</div>
