<div id="cemiterio">

</div>
<div style="margin: 0 auto;width: 900px;">
    <?= $_SESSION['player'] ?>
    <input type="hidden" value="<?= $_SESSION['player'] ?>" id="player">
    <input type="text" value="" id="oponente">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9">
                    <div id="tabuleiro" class="tabuleiro">
                        <div id="taboponente" class="col-lg-12" style="height: 245px;">

                        </div>
                        <div id="tabplayer" class="col-lg-12" style="height: 245px;">

                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div id="mensagens">

                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

<div class="modal fade" id="iniciar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span id="men_modal"> </span> Selecione uma opção</h4>
            </div>
            <div class="modal-body">
                <div class="row col-lg-12">
                    <div class="col-lg-6">
                        <!--<button class="btn btn-default  form-control" onclick="iniciar();">Iniciar</button>-->
                        <button class="btn btn-default  form-control">Opções</button>
                        <button class="btn btn-default  form-control" onclick="conectar();">Conectar</button>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div id="conectados">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="maojogador">
    <div class="col-lg-12">

    </div>
</div>
