<div id="cemiterio">

</div>
<div style="margin: 0 auto;width: 900px;">
    <input type="hidden" value="<?= $_SESSION['player'] ?>" id="player">
    <div class="row">
        <div class="col-lg-5">
            <input type="text" value="<?= $_SESSION['player'] ?>" id="jogador" readonly="true" class="exibivel form-control">
        </div>
        <div class="col-lg-2">
            <span class="form-control text-danger"> Contra </span>
        </div>
        <div class="col-lg-5">
            <input type="text" value="" id="oponente" readonly="true" class="exibivel form-control">
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    <div id="tabuleiro" class="tabuleiro form-control">
                        <div id="taboponente" class="col-lg-12" style="height: 245px;">

                        </div>
                        <div id="tabplayer" class="col-lg-12" style="height: 245px;">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="top: 55px; position: absolute;right: 40px;" draggable="true">
    <div class="row">
        <div class="col-lg-12">
            <div id="mensagens" class="form-control" style="display: block;height: 300px;overflow: auto;"></div>

        </div>
        <div class="col-lg-9">
            <input type="text" class="form-control" id="men_envia"/>
        </div>
        <div class="col-lg-3">
            <button type="button" class="btn btn-default form-control" onclick="conversar();">Enviar</button>
        </div>
    </div>

</div>


<div class="modal fade" id="adversarios" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content modal-sm">
            <div class="modal-header bg-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><span></span> Selecione um adversario</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div id="conectados">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="maojogador" class="maojogador">
    <div class="col-lg-12" id="controles">
        <div class="col-lg-2">
            <button type="button" onclick="conectar();" id="btnacao" class="btn btn-danger form-control">Conectar</button>
        </div>
    </div>
    <div class="col-lg-12" id="cartas"></div>
</div>
