<!DOCTYPE html>
<html>
    <header>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Demo - Projeto com Jaspion</title>
        <?= $this->css('bootstrap-theme.min') ?>"
        <?= $this->css('bootstrap.min') ?>
        <?= $this->css('padrao') ?>
    </header>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <ul class="nav navbar-nav">
                <li><a><span class="glyphicon glyphicon-globe"></span> <span class="h4">Jaspion Demo</span></a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->link("/cardgame"); ?>"><span>Card Game</span></a></li>
            </ul>
        </nav>
        <div style="margin-top: 50px;">
            <div class="panel panel-danger">
                <div class="panel-heading "><span class="panel-title">Jaspion Framework Demo</span></div>
                <div class="panel-body" style="min-height: 500px;">
                    <div class='alerta'>
                        <?php echo $this->view->mensagem; ?>
                    </div>
                    <?php $this->content(); ?>
                </div>
                <div class="panel-footer">
                    <div class="text-center small">
                        Desenvolvido Por
                        <span class="glyphicon glyphicon-fire"></span> Gilmario Software -
                        <span class="glyphicon glyphicon-glass"></span> Antonio Allan -
                        todos os direitos reservados <span class="glyphicon glyphicon-random"></span>
                    </div>
                </div>
            </div>
        </div>

        <div id="erro"></div>
        <?= $this->js('jquery-1.10.2.min') ?>
        <?= $this->js('bootstrap.min') ?>
        <?php $this->scripts(); ?>
    </body>
</html>